steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'asia-northeast1-docker.pkg.dev/m2m-core/rfid-cloud-api/linen-api',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-northeast1-docker.pkg.dev/m2m-core/rfid-cloud-api/linen-api'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'rfid-cloud-api'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/m2m-core/rfid-cloud-api/linen-api'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-northeast1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GCP_PROJECT=m2m-core,GCP_LOCATION=asia-northeast1,TASK_QUEUE_NAME=rfid-task-queue,TARGET_URL=https://rfid-cloud-api-829912128848.asia-northeast1.run.app/sync/large-rfid'

images:
  - asia-northeast1-docker.pkg.dev/m2m-core/rfid-cloud-api/linen-api
